In [1]:
#importing libraries
from dateutil.parser import parse 
import matplotlib as mpl
import matplotlib.pyplot as plt
import seaborn as sns
import numpy as np
import pandas as pd

In [2]:
# reading in the data file
df = pd.read_csv('/Users/kratipatidar/Desktop/prof_nara/data/data_corr.csv')
df

            bg_dest  date_start  dev_count       bg_orig            POI
0       60730056002  2020-01-01          1  420490110012    Balboa Park
1       60730056002  2020-01-01          1  361031580014    Balboa Park
2       60730056002  2020-01-01          1  120010018131    Balboa Park
3       60730056002  2020-01-01          1  121270825071    Balboa Park
4       60730056002  2020-01-01          1  110010009012    Balboa Park
...             ...         ...        ...           ...            ...
242606  60730212021  2020-09-21          2   40270111042  Viejas Casino
242607  60730212021  2020-09-21          1   60650464022  Viejas Casino
242608  60730212021  2020-09-21          1   60250117001  Viejas Casino
242609  60730212021  2020-09-21          1   60250107001  Viejas Casino
242610  60730079101  2020-09-21          1  150030074001  Mission Beach

[242611 rows x 5 columns]

In [ ]:
# let's pivot this table

df_pt = pd.pivot_table(df, )

In [8]:
# reading in the income and age (combined) file

inc_age = pd.read_csv('/Users/kratipatidar/Desktop/prof_nara/data/inc_age.csv')
inc_age.head()

,Unnamed: 0,TractID,geometry,income,percent_20_24,percent_25_34,percent_35_44,percent_45_54,percent_55_59,percent_60_64,percent_65_74,percent_75_84,percent_over_85,percent_over_62
0,0,6073017034,"POLYGON ((-117.101805 32.996934, -117.100896 3...",118750.0,6.0,15.8,14.8,13.7,6.5,5.6,8.8,1.4,0.4,13.5
1,1,6073017014,"POLYGON ((-117.071 33.013903, -117.070513 33.0...",62052.0,0.0,2.6,2.6,2.8,9.9,8.0,30.5,23.2,20.3,79.2
2,2,6073017104,"POLYGON ((-117.248387 33.045653, -117.248331 3...",126765.0,3.5,7.9,13.4,12.3,9.4,8.7,12.7,4.4,1.7,24.5
3,3,6073018504,"POLYGON ((-117.356179 33.189215, -117.356016 3...",90263.0,5.5,9.0,16.3,12.9,8.9,8.5,7.7,6.0,1.4,17.8
4,4,6073007501,"POLYGON ((-117.244607 32.748195, -117.244435 3...",69563.0,6.0,34.5,23.2,12.1,4.1,3.9,6.6,0.5,0.6,8.9

In [9]:
# we will add a orig_tract column in df for merging with the inc_age dataframe

df['orig_tract'] = df['bg_orig'].floordiv(10)
df

,bg_dest,date_start,dev_count,bg_orig,POI,orig_tract
0,60730056002,2020-01-01,1,420490110012,Balboa Park,42049011001
1,60730056002,2020-01-01,1,361031580014,Balboa Park,36103158001
2,60730056002,2020-01-01,1,120010018131,Balboa Park,12001001813
3,60730056002,2020-01-01,1,121270825071,Balboa Park,12127082507
4,60730056002,2020-01-01,1,110010009012,Balboa Park,11001000901
...,...,...,...,...,...,...
242606,60730212021,2020-09-21,2,40270111042,Viejas Casino,4027011104
242607,60730212021,2020-09-21,1,60650464022,Viejas Casino,6065046402
242608,60730212021,2020-09-21,1,60250117001,Viejas Casino,6025011700
242609,60730212021,2020-09-21,1,60250107001,Viejas Casino,6025010700
242610,60730079101,2020-09-21,1,150030074001,Mission Beach,15003007400

In [10]:
# now we merge the two dataframes

df_inc_age = pd.merge(df, inc_age,  how='inner', left_on=['orig_tract'], right_on = ['TractID'])
df_inc_age.head()

,bg_dest,date_start,dev_count,bg_orig,POI,orig_tract,Unnamed: 0,TractID,geometry,income,percent_20_24,percent_25_34,percent_35_44,percent_45_54,percent_55_59,percent_60_64,percent_65_74,percent_75_84,percent_over_85,percent_over_62
0,60730056002,2020-01-01,1,60730046002,Balboa Park,6073004600,61,6073004600,"POLYGON ((-117.14759 32.717865, -117.14756 32....",57329.0,7.7,36.4,18.7,11.1,1.5,7.6,6.7,2.3,0.0,13.7
1,60730056002,2020-01-01,1,60730046001,Balboa Park,6073004600,61,6073004600,"POLYGON ((-117.14759 32.717865, -117.14756 32....",57329.0,7.7,36.4,18.7,11.1,1.5,7.6,6.7,2.3,0.0,13.7
2,60730056002,2020-01-02,1,60730046001,Balboa Park,6073004600,61,6073004600,"POLYGON ((-117.14759 32.717865, -117.14756 32....",57329.0,7.7,36.4,18.7,11.1,1.5,7.6,6.7,2.3,0.0,13.7
3,60730056002,2020-01-03,1,60730046001,Balboa Park,6073004600,61,6073004600,"POLYGON ((-117.14759 32.717865, -117.14756 32....",57329.0,7.7,36.4,18.7,11.1,1.5,7.6,6.7,2.3,0.0,13.7
4,60730056002,2020-01-04,1,60730046002,Balboa Park,6073004600,61,6073004600,"POLYGON ((-117.14759 32.717865, -117.14756 32....",57329.0,7.7,36.4,18.7,11.1,1.5,7.6,6.7,2.3,0.0,13.7

In [14]:
# we segregate the above dataframe into 3 parts

jan_wk = df_inc_age[(df_inc_age['date_start'] >= '2020-01-01') & (df_inc_age['date_start'] <= '2020-01-08')]
jan_wk

,bg_dest,date_start,dev_count,bg_orig,POI,orig_tract,Unnamed: 0,TractID,geometry,income,percent_20_24,percent_25_34,percent_35_44,percent_45_54,percent_55_59,percent_60_64,percent_65_74,percent_75_84,percent_over_85,percent_over_62
0,60730056002,2020-01-01,1,60730046002,Balboa Park,6073004600,61,6073004600,"POLYGON ((-117.14759 32.717865, -117.14756 32....",57329.0,7.7,36.4,18.7,11.1,1.5,7.6,6.7,2.3,0.0,13.7
1,60730056002,2020-01-01,1,60730046001,Balboa Park,6073004600,61,6073004600,"POLYGON ((-117.14759 32.717865, -117.14756 32....",57329.0,7.7,36.4,18.7,11.1,1.5,7.6,6.7,2.3,0.0,13.7
2,60730056002,2020-01-02,1,60730046001,Balboa Park,6073004600,61,6073004600,"POLYGON ((-117.14759 32.717865, -117.14756 32....",57329.0,7.7,36.4,18.7,11.1,1.5,7.6,6.7,2.3,0.0,13.7
3,60730056002,2020-01-03,1,60730046001,Balboa Park,6073004600,61,6073004600,"POLYGON ((-117.14759 32.717865, -117.14756 32....",57329.0,7.7,36.4,18.7,11.1,1.5,7.6,6.7,2.3,0.0,13.7
4,60730056002,2020-01-04,1,60730046002,Balboa Park,6073004600,61,6073004600,"POLYGON ((-117.14759 32.717865, -117.14756 32....",57329.0,7.7,36.4,18.7,11.1,1.5,7.6,6.7,2.3,0.0,13.7
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
161074,60730212021,2020-01-08,1,60730033011,Viejas Casino,6073003301,372,6073003301,"POLYGON ((-117.10971 32.708985, -117.109557 32...",47174.0,6.8,16.3,13.5,10.1,4.6,2.7,1.8,2.6,1.3,6.7
161255,60730056002,2020-01-07,1,60730101041,Balboa Park,6073010104,94,6073010104,"POLYGON ((-117.101403 32.576504, -117.101213 3...",61801.0,10.3,12.3,13.9,11.2,8.0,6.1,7.5,3.5,1.6,17.2
161256,60730056002,2020-01-08,1,60730101042,Balboa Park,6073010104,94,6073010104,"POLYGON ((-117.101403 32.576504, -117.101213 3...",61801.0,10.3,12.3,13.9,11.2,8.0,6.1,7.5,3.5,1.6,17.2
161352,60730056002,2020-01-07,2,60730197013,Balboa Park,6073019701,36,6073019701,"POLYGON ((-117.279581 33.186606, -117.279574 3...",78300.0,7.4,22.3,14.5,11.9,6.7,5.1,4.4,4.9,1.5,13.4
161422,60730056002,2020-01-08,1,60730083131,Balboa Park,6073008313,98,6073008313,"POLYGON ((-117.247446 32.848312, -117.247334 3...",194643.0,4.2,6.5,9.0,13.3,5.3,8.9,13.5,11.2,3.5,33.7

In [12]:
pre_ld

,bg_dest,dev_count,bg_orig,orig_tract,Unnamed: 0,TractID,income,percent_20_24,percent_25_34,percent_35_44,percent_45_54,percent_55_59,percent_60_64,percent_65_74,percent_75_84,percent_over_85,percent_over_62
bg_dest,1.000000,0.024757,0.196308,0.196308,-0.054829,0.196308,-0.063721,-0.016896,-0.120271,-0.084359,0.005094,0.082254,0.091688,0.060310,0.014089,0.000444,0.050777
dev_count,0.024757,1.000000,0.006515,0.006515,0.018984,0.006515,0.007408,-0.005995,0.051190,0.011366,-0.066178,-0.008891,0.014749,0.045073,0.002383,-0.034854,0.017282
bg_orig,0.196308,0.006515,1.000000,1.000000,-0.069554,1.000000,0.244832,-0.129572,-0.443128,-0.228101,0.152146,0.304149,0.247218,0.230197,0.169872,0.095055,0.226887
orig_tract,0.196308,0.006515,1.000000,1.000000,-0.069553,1.000000,0.244833,-0.129571,-0.443129,-0.228102,0.152147,0.304149,0.247217,0.230196,0.169872,0.095053,0.226886
Unnamed: 0,-0.054829,0.018984,-0.069554,-0.069553,1.000000,-0.069553,0.076338,0.022651,0.103528,0.108799,-0.036088,-0.052578,0.033993,-0.101880,-0.067702,-0.051592,-0.085414
TractID,0.196308,0.006515,1.000000,1.000000,-0.069553,1.000000,0.244833,-0.129571,-0.443129,-0.228102,0.152147,0.304149,0.247217,0.230196,0.169872,0.095053,0.226886
income,-0.063721,0.007408,0.244832,0.244833,0.076338,0.244833,1.000000,-0.324835,-0.363857,0.028663,0.384604,0.400096,0.367762,0.429902,0.280790,0.123325,0.400602
percent_20_24,-0.016896,-0.005995,-0.129572,-0.129571,0.022651,-0.129571,-0.324835,1.000000,0.157183,-0.221602,-0.490038,-0.446499,-0.399903,-0.406056,-0.324911,-0.153599,-0.419164
percent_25_34,-0.120271,0.051190,-0.443128,-0.443129,0.103528,-0.443129,-0.363857,0.157183,1.000000,0.274241,-0.404771,-0.394659,-0.403375,-0.427492,-0.380338,-0.237591,-0.459998
percent_35_44,-0.084359,0.011366,-0.228101,-0.228102,0.108799,-0.228102,0.028663,-0.221602,0.274241,1.000000,0.062234,-0.212898,-0.224757,-0.257610,-0.286680,-0.222669,-0.299161
percent_45_54,0.005094,-0.066178,0.152146,0.152147,-0.036088,0.152147,0.384604,-0.490038,-0.404771,0.062234,1.000000,0.318179,0.202530,0.216305,0.137387,-0.013474,0.193668
percent_55_59,0.082254,-0.008891,0.304149,0.304149,-0.052578,0.304149,0.400096,-0.446499,-0.394659,-0.212898,0.318179,1.000000,0.471035,0.470330,0.335160,0.210147,0.469436
percent_60_64,0.091688,0.014749,0.247218,0.247217,0.033993,0.247217,0.367762,-0.399903,-0.403375,-0.224757,0.202530,0.471035,1.000000,0.580446,0.479706,0.319986,0.693325
percent_65_74,0.060310,0.045073,0.230197,0.230196,-0.101880,0.230196,0.429902,-0.406056,-0.427492,-0.257610,0.216305,0.470330,0.580446,1.000000,0.646656,0.410422,0.903262
percent_75_84,0.014089,0.002383,0.169872,0.169872,-0.067702,0.169872,0.280790,-0.324911,-0.380338,-0.286680,0.137387,0.335160,0.479706,0.646656,1.000000,0.537589,0.849552
percent_over_85,0.000444,-0.034854,0.095055,0.095053,-0.051592,0.095053,0.123325,-0.153599,-0.237591,-0.222669,-0.013474,0.210147,0.319986,0.410422,0.537589,1.000000,0.641337
percent_over_62,0.050777,0.017282,0.226887,0.226886,-0.085414,0.226886,0.400602,-0.419164,-0.459998,-0.299161,0.193668,0.469436,0.693325,0.903262,0.849552,0.641337,1.000000